services:
  frontend01:
    image: nginx:1.29.6-alpine
    container_name: f01
    volumes:
      - ./f01/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./f01/html:/etc/nginx/html:ro
    ports:
      - "82:80"
    restart: unless-stopped
    networks:
      local-net:
        ipv4_address: 10.10.40.30

  frontend02:
    image: nginx:1.29.6-alpine
    container_name: f02
    volumes:
      - ./f02/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./f02/html:/etc/nginx/html:ro
    ports:
      - "83:80"
    restart: unless-stopped
    networks:
      local-net:
        ipv4_address: 10.10.40.31

  haproxy01:
    image: haproxy:3.3.4
    container_name: h01
    volumes:
      - ./haproxy01.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: unless-stopped
    networks:
      local-net:
        ipv4_address: 10.10.40.20
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    depends_on:
      - frontend01

  haproxy02:
    image: haproxy:3.3.4
    container_name: h02
    volumes:
      - ./haproxy02.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: unless-stopped
    networks:
      local-net:
        ipv4_address: 10.10.40.21
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    depends_on:
      - frontend02


  keepalived01:
    image: shawly/keepalived:2.3.1
    container_name: k01
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      KEEPALIVED_CUSTOM_CONFIG: "true"
    volumes:
      - ./keepalived01.conf:/etc/keepalived/keepalived.conf:ro
    network_mode: "service:haproxy01"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    depends_on:
      - haproxy01

  keepalived02:
    image: shawly/keepalived:2.3.1
    container_name: k02
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      KEEPALIVED_CUSTOM_CONFIG: "true"
    volumes:
      - ./keepalived02.conf:/etc/keepalived/keepalived.conf:ro
    network_mode: "service:haproxy02"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    depends_on:
      - haproxy02

networks:
  local-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: haweb0
    ipam:
      config:
        - subnet: 10.10.40.0/24
          gateway: 10.10.40.1
