global_defs {
    router_id h01
}

vrrp_instance web {
    state MASTER
    interface eth0
    virtual_router_id 100
    priority 101
    advert_int 1
    unicast_src_ip 10.10.40.20
    unicast_peer {
        10.10.40.21
    }
    authentication {
        auth_type PASS
        auth_pass myPass12
    }
    virtual_ipaddress {
        10.10.40.40
    }
}